### ISSUE TITLE
Use PHLivePhotoView for preview in livephoto sandbox

### ISSUE THREAD

**Issue by banjun** [mzp/LoveLiver#10]
Happy WWDC 2016! 🎉 

``` swift
@available(OSX 10.12, *)
public class PHLivePhotoView : NSView
```

Try using PHLivePhotoView if it can be used without saving PHLivePhoto.

Other topics I confirmed at WWDC...
- there is no API for creating Live Photos from any arbitrary JPEG and MOV.
- only way to generate Live Photos without iOS Device is to manipulate maker metadata with paired UUID (currently LoveLiver do so).
- there is no public UTI, MIME type, nor single serialized livephoto file format for sharing.
- currently server can check whether any pair of image and movie is a live photo, only by checking UUIDs in maker metadata contained in the files.

As a reminder...

Screenshots of beta apple softwares cannot be published.

**Comment by banjun** [comment]
close the one year old issue due to lack of availability of PHLivePhotoView in macOS.

> In macOS, Live Photo objects are available only when editing Live Photo content in a photo editing extension that runs in the Photos app

https://developer.apple.com/documentation/photosui/phlivephotoview

for the other part of the issue, we should migrate to HEIF live photo.

**Comment by iotsupport** [comment]
Gracias por tu mensaje al buzón de soporte de la Plataforma
IoT de Telefónica, te responderemos lo antes posible.

On June 28, 2017 at 10:23 AM mzp/LoveLiver wrote:

close the one year old issue due to lack of availability of
PHLivePhotoView in macOS.

> In macOS, Live Photo objects are available only when editing
Live Photo content in a photo editing extension that runs in the
Photos app

https://developer.apple.com/documentation/photosui/phlivephotoview
( https://developer.apple.com/documentation/photosui/phlivephotoview )

for the other part of the issue, we should migrate to HEIF live
photo.

--

You are receiving this because you are subscribed to this thread.

Reply to this email directly or view it on GitHub:

https://github.com/mzp/LoveLiver/issues/10#issuecomment-311591454
( https://github.com/mzp/LoveLiver/issues/10#issuecomment-311591454 )

_______________________________________________

Iot_support mailing list

Iot_support@tid.es ( mailto:Iot_support@tid.es )

https://listas.tid.es/mailman/listinfo/iot_support ( https://listas.tid.es/mailman/listinfo/iot_support )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=iot+partners&uv_contact_url=iot-partners.uservoice.com&uv_experience=email )
