### ISSUE TITLE
Support Touch Bar

### ISSUE THREAD

**Issue by banjun** [mzp/LoveLiver#11]
Idea:
- movie overview for each window
- scope adjustment control for live photo sandbox popover

**Comment by iotsupport** [comment]
Gracias por tu mensaje al buzón de soporte de la Plataforma
IoT de Telefónica, te responderemos lo antes posible.

On October 28, 2016 at 2:46 AM mzp/LoveLiver wrote:

Idea:

* movie overview for each window

* scope adjustment control for live photo sandbox popover

--

You are receiving this because you are subscribed to this thread.

Reply to this email directly or view it on GitHub:

https://github.com/mzp/LoveLiver/issues/11 ( https://github.com/mzp/LoveLiver/issues/11 )

_______________________________________________

Iot_support mailing list

Iot_support@tid.es ( mailto:Iot_support@tid.es )

https://listas.tid.es/mailman/listinfo/iot_support ( https://listas.tid.es/mailman/listinfo/iot_support )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=iot+partners&uv_contact_url=iot-partners.uservoice.com&uv_experience=email )

**Comment by banjun** [comment]
@iotsupport can you disable auto response to the github notifications?

**Comment by mzp** [comment]
yeah! now touchbar is supported!
