### ISSUE TITLE
How can i add more seconds? 

### ISSUE THREAD

**Issue by brown220310** [mzp/LoveLiver#17]
Hello,

Please how can i add more seconds, the app make a live wallpaper with 3sec, is it possible to make 10sec for one live wallpaper?

Thanks

**Comment by iotsupport** [comment]
Gracias por tu mensaje al buzón de soporte de la Plataforma
IoT de Telefónica, te responderemos lo antes posible.

On May 02, 2017 at 1:12 PM mzp/LoveLiver wrote:

Hello,

Please how can i add more seconds, the app make a live wallpaper
with 3sec, is it possible to make 10sec for one live wallpaper?

Thanks

--

You are receiving this because you are subscribed to this thread.

Reply to this email directly or view it on GitHub:

https://github.com/mzp/LoveLiver/issues/17 ( https://github.com/mzp/LoveLiver/issues/17 )

_______________________________________________

Iot_support mailing list

Iot_support@tid.es ( mailto:Iot_support@tid.es )

https://listas.tid.es/mailman/listinfo/iot_support ( https://listas.tid.es/mailman/listinfo/iot_support )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=iot+partners&uv_contact_url=iot-partners.uservoice.com&uv_experience=email )

**Comment by Fawxy** [comment]
Change livePhotoDuration in LivePhotoSandboxViewController.swift

**Comment by iotsupport** [comment]
Gracias por tu mensaje al buzón de soporte de la Plataforma
IoT de Telefónica, te responderemos lo antes posible.

On December 13, 2017 at 6:49 PM mzp/LoveLiver wrote:

Change livePhotoDuration in
LivePhotoSandboxViewController.swift

--

You are receiving this because you commented.

Reply to this email directly or view it on GitHub:

https://github.com/mzp/LoveLiver/issues/17#issuecomment-351468774
( https://github.com/mzp/LoveLiver/issues/17#issuecomment-351468774 )

_______________________________________________

Iot_support mailing list

Iot_support@tid.es ( mailto:Iot_support@tid.es )

https://listas.tid.es/mailman/listinfo/iot_support ( https://listas.tid.es/mailman/listinfo/iot_support )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=iot+partners&uv_contact_url=iot-partners.uservoice.com&uv_experience=email )

**Comment by mzp** [comment]
It is possible, but I think 3sec is good to use same duration as Apple's LivePhoto.

Off course, you can edit source code and build and use it.

**Comment by iotsupport** [comment]
Gracias por tu mensaje al buzón de soporte de la Plataforma
IoT de Telefónica, te responderemos lo antes posible.

On December 14, 2017 at 3:41 AM mzp/LoveLiver wrote:

It is possible, but I think 3sec is good to use same duration
as Apple's LivePhoto.

Off course, you can edit source code and build and use it.

--

You are receiving this because you commented.

Reply to this email directly or view it on GitHub:

https://github.com/mzp/LoveLiver/issues/17#issuecomment-351591420
( https://github.com/mzp/LoveLiver/issues/17#issuecomment-351591420 )

_______________________________________________

Iot_support mailing list

Iot_support@tid.es ( mailto:Iot_support@tid.es )

https://listas.tid.es/mailman/listinfo/iot_support ( https://listas.tid.es/mailman/listinfo/iot_support )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=iot+partners&uv_contact_url=iot-partners.uservoice.com&uv_experience=email )

**Comment by iotsupport** [comment]
Gracias por tu mensaje al buzón de soporte de la Plataforma
IoT de Telefónica, te responderemos lo antes posible.

On December 14, 2017 at 3:41 AM mzp/LoveLiver wrote:

Closed #17.

--

You are receiving this because you commented.

Reply to this email directly or view it on GitHub:

https://github.com/mzp/LoveLiver/issues/17#event-1386896416 ( https://github.com/mzp/LoveLiver/issues/17#event-1386896416 )

_______________________________________________

Iot_support mailing list

Iot_support@tid.es ( mailto:Iot_support@tid.es )

https://listas.tid.es/mailman/listinfo/iot_support ( https://listas.tid.es/mailman/listinfo/iot_support )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=iot+partners&uv_contact_url=iot-partners.uservoice.com&uv_experience=email )
