### ISSUE TITLE
Support Portrait Movies in Small Displays

### ISSUE THREAD

**Issue by banjun** [mzp/LoveLiver#9]
As there is no explicit upper limits regarding screen size in the live photo sandbox popover, in smaller screen (e.g. 12-inch MacBook) iPhone portrait size movies may cause overflowed UI against the screen.

**Comment by iotsupport** [comment]
Gracias por tu mensaje al buzón de soporte de la Plataforma
IoT de Telefónica, te responderemos lo antes posible.

On November 20, 2016 at 3:24 PM mzp/LoveLiver wrote:

Closed #9 via #14.

--

You are receiving this because you are subscribed to this thread.

Reply to this email directly or view it on GitHub:

https://github.com/mzp/LoveLiver/issues/9#event-865620355 ( https://github.com/mzp/LoveLiver/issues/9#event-865620355 )

_______________________________________________

Iot_support mailing list

Iot_support@tid.es ( mailto:Iot_support@tid.es )

https://listas.tid.es/mailman/listinfo/iot_support ( https://listas.tid.es/mailman/listinfo/iot_support )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=iot+partners&uv_contact_url=iot-partners.uservoice.com&uv_experience=email )
